-- Generated SQL to populate spotify_tracks table
-- Generated on: 2025-09-13T20:32:51.909Z
-- Total tracks: 33

INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:56YasbqXFzP3ErHyhLtn26', 'ALL THE TIME', 'Forrest Frank, nobigdyl.', 168421, '{}'::text[], '{}'::text[], NULL, 162);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:2pwYfIGr9Jmk6HpbDDMrpe', 'HIM', 'Jon Keith, Miles Minnick', 168687, '{}'::text[], '{}'::text[], 6, 163);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:1mL3MVPYMXMXx8vB93ytTP', 'CIEN DOCENAS', 'WHATUPRG', 98015, '{}'::text[], '{}'::text[], 31, 96);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:55wFmVPoWFRwdyFw3ngSRz', 'REIGN DOWN', 'Scootie Wop', 126332, '{}'::text[], '{}'::text[], 15, 110);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:1oWpZUAbdXCJt9ZNN6nFOG', 'Lay Down II', 'Trip Lee', 172394, '{}'::text[], '{}'::text[], 17, 159);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:2Q1bfpjE2DwKnn6yLIYZdZ', 'RIO', 'WHATUPRG, Nesk Only', 176363, '{}'::text[], '{}'::text[], NULL, 160);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:0GHY3CW19K5KqIBjrJdZGz', 'LOOK AT GOD', 'Wxlf, Jon Keith', 143456, '{}'::text[], '{}'::text[], NULL, 123);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:469LAygB7nTl7CCDbnniaR', 'Son Is Always Shining', 'J-Blev, Selah the Corner', 151727, '{}'::text[], '{}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:6NVlLjo4Y4eaNYkXv4tScU', 'The Punchline Academy Cypher', 'Datin, C4 Crotona, Selah the Corner', 413469, '{}'::text[], '{}'::text[], 5, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:6AlQ5HtGrPQO7M20pTtsf5', 'City on His Back', 'J. Monty', 203570, '{}'::text[], '{}'::text[], 28, 197);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:3mtfe81bb7wsMtQPbWpOMY', 'receipt', 'gio., Dell Mac', 148732, '{}'::text[], '{}'::text[], 13, 144);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:6868cDsJrSGPyYnO8HPxHZ', 'ROB HELL', 'indie tribe, nobigdyl., Torey D''Shaun, Jon Keith', 151173, '{}'::text[], '{}'::text[], 10, 148);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:57Il3OuTJdiF42Qwz1A17n', 'Day One', 'Childlike CiCi, Lecrae', 187692, '{}'::text[], '{}'::text[], 11, 184);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:4MgpHcDBkz2k84ao1BrBHK', 'DROP!', 'Forrest Frank', 234271, '{}'::text[], '{}'::text[], 5, 232);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:27SV91JVfJNMvvDoCu5IM7', 'No Remorse', 'Caleb Gordon', 202714, '{}'::text[], '{}'::text[], 17, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:2CQNa8WplamGGPnMpSlFt6', 'Matthew 18:20', 'Alex Jean, De La Cruz', 168046, '{}'::text[], '{}'::text[], NULL, 164);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:2ImsqbD8uYAwKH358qcGie', 'Pop Out', 'Trendsetter Sense, BigBreeze, Kijan Boone', 147701, '{}'::text[], '{}'::text[], 15, 144);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:0PgnIPWS1eQh1SbneVtFDB', 'NOBODY BUT GOD (feat. Jon Keith)', 'Aaron Cole, Parris Chariz, Jon Keith', 158490, '{}'::text[], '{}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:7Jerd3W7J7CvqX6SeYiF3K', 'Tell No Lie', 'Lecrae, Jackie Hill Perry', 144650, '{}'::text[], '{}'::text[], 12, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:6qTRyyctUgRWY5HqbndlAs', 'Goliath', 'Edify, Tds Cam', 168050, '{}'::text[], '{}'::text[], 10, 160);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:1sYPiSou59AOcqM7Dwi8wv', 'NO MATTER WHAT', 'indie tribe, nobigdyl., Jon Keith, DJ Mykael V, Mogli the Iceburg, Torey D''Shaun', 251706, '{}'::text[], '{}'::text[], 4, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:6PjYVEj03iPG81ZfwA9D3y', 'Outsiiide', 'Miles Minnick', 152307, '{}'::text[], '{}'::text[], 20, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:2Cy8awXmK3RJvwZrDHIqOj', 'REVIVAL!', 'nobigdyl., KB', 184865, '{}'::text[], '{}'::text[], NULL, 182);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:4xmrP0u72ox9OJ1cgJzZpQ', 'Lion King', 'R.kitect, RJ Payne, m1L', 233611, '{}'::text[], '{}'::text[], 19, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:2pTIbtODPQ9dtQuD3rPaTp', 'GTA 6', 'Andy Mineo, Wordsplayed, Magic & Bird', 167667, '{}'::text[], '{}'::text[], 20, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:57TsydrFWLVhEFtJZTVcWB', 'God Did II', 'RUA YOUNG, KB', 159621, '{}'::text[], '{}'::text[], 5, 156);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:2TCgkRY4Og8Q0I52ksHDyG', 'WHAT THEY GON DO', 'Gavin the HotRod', 171850, '{}'::text[], '{}'::text[], NULL, 156);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:2Yz9Rtpswoz6JIHItcULU5', 'In My Bag', 'Alex Jean, Kijan Boone', 133846, '{}'::text[], '{}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:1QRxu30D9RdCpff2VpJWY7', 'Okayyy We Back', 'Andy Mineo, Mark Morrison', 166765, '{}'::text[], '{}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:3WN17zGd3yNhnHrRx15dXh', 'Keanu''s Song', 'KB, KEANU', 152911, '{}'::text[], '{}'::text[], 5, 149);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:7JiUCSSulfaJJEKWiZjVNG', 'KEEP GOIN', 'Tommy Zuko', 140000, '{}'::text[], '{}'::text[], NULL, 132);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:6YbsIDsK3A58cogFEXHlvY', 'KEEP IT UP', 'TUVÍ, NAES', 198367, '{}'::text[], '{}'::text[], 18, 175);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:4EC3Ug5LdFDCYI8AXtXsZx', 'Yet', '1K Phew, 1k Pson', 151956, '{}'::text[], '{}'::text[], 6, 151);