-- Generated SQL to populate spotify_tracks table
-- Generated on: 2025-09-13T21:46:42.730Z
-- Total workout tracks: 33
-- Total rest tracks: 40
-- Total tracks: 73

-- Workout tracks (hype and bridge)
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:56YasbqXFzP3ErHyhLtn26', 'ALL THE TIME', 'Forrest Frank, nobigdyl.', 168421, '{}'::text[], '{"bridge"}'::text[], NULL, 162);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:2pwYfIGr9Jmk6HpbDDMrpe', 'HIM', 'Jon Keith, Miles Minnick', 168687, '{}'::text[], '{"hype"}'::text[], 6, 163);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:1mL3MVPYMXMXx8vB93ytTP', 'CIEN DOCENAS', 'WHATUPRG', 98015, '{}'::text[], '{"hype"}'::text[], 31, 96);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:55wFmVPoWFRwdyFw3ngSRz', 'REIGN DOWN', 'Scootie Wop', 126332, '{}'::text[], '{"hype"}'::text[], 15, 110);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:1oWpZUAbdXCJt9ZNN6nFOG', 'Lay Down II', 'Trip Lee', 172394, '{}'::text[], '{"hype"}'::text[], 17, 159);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:2Q1bfpjE2DwKnn6yLIYZdZ', 'RIO', 'WHATUPRG, Nesk Only', 176363, '{}'::text[], '{"bridge"}'::text[], NULL, 160);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:0GHY3CW19K5KqIBjrJdZGz', 'LOOK AT GOD', 'Wxlf, Jon Keith', 143456, '{}'::text[], '{"bridge"}'::text[], NULL, 123);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:469LAygB7nTl7CCDbnniaR', 'Son Is Always Shining', 'J-Blev, Selah the Corner', 151727, '{}'::text[], '{"bridge"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:6NVlLjo4Y4eaNYkXv4tScU', 'The Punchline Academy Cypher', 'Datin, C4 Crotona, Selah the Corner', 413469, '{}'::text[], '{"hype"}'::text[], 5, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:6AlQ5HtGrPQO7M20pTtsf5', 'City on His Back', 'J. Monty', 203570, '{}'::text[], '{"hype"}'::text[], 28, 197);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:3mtfe81bb7wsMtQPbWpOMY', 'receipt', 'gio., Dell Mac', 148732, '{}'::text[], '{"hype"}'::text[], 13, 144);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:6868cDsJrSGPyYnO8HPxHZ', 'ROB HELL', 'indie tribe, nobigdyl., Torey D''Shaun, Jon Keith', 151173, '{}'::text[], '{"hype"}'::text[], 10, 148);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:57Il3OuTJdiF42Qwz1A17n', 'Day One', 'Childlike CiCi, Lecrae', 187692, '{}'::text[], '{"hype"}'::text[], 11, 184);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:4MgpHcDBkz2k84ao1BrBHK', 'DROP!', 'Forrest Frank', 234271, '{}'::text[], '{"hype"}'::text[], 5, 232);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:27SV91JVfJNMvvDoCu5IM7', 'No Remorse', 'Caleb Gordon', 202714, '{}'::text[], '{"hype"}'::text[], 17, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:2CQNa8WplamGGPnMpSlFt6', 'Matthew 18:20', 'Alex Jean, De La Cruz', 168046, '{}'::text[], '{"bridge"}'::text[], NULL, 164);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:2ImsqbD8uYAwKH358qcGie', 'Pop Out', 'Trendsetter Sense, BigBreeze, Kijan Boone', 147701, '{}'::text[], '{"hype"}'::text[], 15, 144);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:0PgnIPWS1eQh1SbneVtFDB', 'NOBODY BUT GOD (feat. Jon Keith)', 'Aaron Cole, Parris Chariz, Jon Keith', 158490, '{}'::text[], '{"bridge"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:7Jerd3W7J7CvqX6SeYiF3K', 'Tell No Lie', 'Lecrae, Jackie Hill Perry', 144650, '{}'::text[], '{"hype"}'::text[], 12, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:6qTRyyctUgRWY5HqbndlAs', 'Goliath', 'Edify, Tds Cam', 168050, '{}'::text[], '{"hype"}'::text[], 10, 160);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:1sYPiSou59AOcqM7Dwi8wv', 'NO MATTER WHAT', 'indie tribe, nobigdyl., Jon Keith, DJ Mykael V, Mogli the Iceburg, Torey D''Shaun', 251706, '{}'::text[], '{"hype"}'::text[], 4, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:6PjYVEj03iPG81ZfwA9D3y', 'Outsiiide', 'Miles Minnick', 152307, '{}'::text[], '{"hype"}'::text[], 20, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:2Cy8awXmK3RJvwZrDHIqOj', 'REVIVAL!', 'nobigdyl., KB', 184865, '{}'::text[], '{"bridge"}'::text[], NULL, 182);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:4xmrP0u72ox9OJ1cgJzZpQ', 'Lion King', 'R.kitect, RJ Payne, m1L', 233611, '{}'::text[], '{"hype"}'::text[], 19, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:2pTIbtODPQ9dtQuD3rPaTp', 'GTA 6', 'Andy Mineo, Wordsplayed, Magic & Bird', 167667, '{}'::text[], '{"hype"}'::text[], 20, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:57TsydrFWLVhEFtJZTVcWB', 'God Did II', 'RUA YOUNG, KB', 159621, '{}'::text[], '{"hype"}'::text[], 5, 156);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:2TCgkRY4Og8Q0I52ksHDyG', 'WHAT THEY GON DO', 'Gavin the HotRod', 171850, '{}'::text[], '{"bridge"}'::text[], NULL, 156);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:2Yz9Rtpswoz6JIHItcULU5', 'In My Bag', 'Alex Jean, Kijan Boone', 133846, '{}'::text[], '{"bridge"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:1QRxu30D9RdCpff2VpJWY7', 'Okayyy We Back', 'Andy Mineo, Mark Morrison', 166765, '{}'::text[], '{"bridge"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:3WN17zGd3yNhnHrRx15dXh', 'Keanu''s Song', 'KB, KEANU', 152911, '{}'::text[], '{"hype"}'::text[], 5, 149);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:7JiUCSSulfaJJEKWiZjVNG', 'KEEP GOIN', 'Tommy Zuko', 140000, '{}'::text[], '{"bridge"}'::text[], NULL, 132);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:6YbsIDsK3A58cogFEXHlvY', 'KEEP IT UP', 'TUVÍ, NAES', 198367, '{}'::text[], '{"hype"}'::text[], 18, 175);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:4EC3Ug5LdFDCYI8AXtXsZx', 'Yet', '1K Phew, 1k Pson', 151956, '{}'::text[], '{"hype"}'::text[], 6, 151);

-- Rest tracks
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:2gmqnkY0jrfz3vnO4FVS4p', 'GOD IS GOOD', 'Forrest Frank, Caleb Gordon', 207529, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:66hLgDd6kk3GfzLej7t2eH', 'Spread The Opps', 'Lecrae', 181290, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:2GrIebBWhOlOVe7yykx50i', 'Christlike', 'Miles Minnick', 159230, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:1ezVmdzA61xULe4dx1Slba', 'BIG G.O.D', 'Red Tips', 145930, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:7I079hnzaP3BNu5Ra7h6q4', 'Set Me Free', 'Lecrae, YK Osiris', 177474, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:0EhihOUNnUG2rK9Z7ao4i5', 'Bibles over Birkins', 'Richdanfamous', 132949, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:0xn6LxYghEct04MQTcrtrJ', 'Armies', 'KB', 210783, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:7h2yzh9vIBxSBN3885QyQt', 'God Taught Me', 'Zauntee', 231230, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:56Q2OtRzToYHKxU9p6XWsn', 'Supernatural', 'Trip Lee', 140554, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:4JR9blNFjAUiybd7RLYfkx', 'Holy Spirit', 'Hulvey', 204679, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:1eU3EhUwOa4a3qCM45HogQ', 'Restored', 'Lecrae, Anike, 1K Phew, Hulvey', 276584, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:0GSEIffBQyILlI6FPzn6G0', 'Altar', 'Hulvey, Forrest Frank', 214850, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:5HumzUY33Lrl13NUjGGKr8', 'Eyes On You', 'Dell Mac', 179200, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:6PwW1zy9hmcP1VqqJaTcvo', 'Chosen', 'Jay Manwell', 136811, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:7HX3ubSk3OVg7ymt5UCYpL', 'Heaven Up Above', 'Hulvey', 201214, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:7iSuMiRlJNceKCE3ES6HBr', 'Lord & Savior', 'Sam Rivera, Limoblaze', 173771, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:1zmxmacvgIcfC9VtKJ1SFl', 'Church in 30', 'Jay Manwell', 183092, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:2TCyoBUM7MNalMXmEQRlX8', 'All For You', 'Hulvey', 212695, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:3OWBvbyAMnKuZLviZ82hIr', 'ALL I NEED', 'Forrest Frank, Hulvey', 203443, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:0b79SWKCzxsKmuG5CBmeDs', 'Perry Lane', 'Hulvey', 190504, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:6ZW8f8xNkauNEKBQthQaas', 'The One Where I Talk To God', 'Marty, Andy Mineo, Tree Giants', 201578, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:08iD88iFwW334KopqK0b8u', 'God On My Side', 'Social Club Misfits, Ty Brasel', 203302, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:7eRU4hubXFooI0Qa7qouXM', 'More Than I Can Bear', 'J. Monty', 201864, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:322Be9xdBaPhiB8rX6BVls', 'Destiny', 'Ty Brasel', 159857, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:21CDBaCTL0ZVJCSZNpBHFe', 'Paradise', '1K Phew', 201461, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:0IP3Dd9qchwml3dwBRnlda', 'ALRIGHT', 'Kaleb Mitchell', 196000, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:2346Isr3M7QwGz5XyMeagQ', 'Rush', 'Cortes', 175804, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:5lf8XNZKRv6rtbPzGoGd7S', 'Let Go', 'Saint James', 157200, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:4V7VTQQWHOCGNRy7iaFHLS', 'It''s a Function', 'Justin Goss, V. Rose', 160052, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:0auEaQZbRnomyp95qDher2', 'Impact', 'Sarah Nathalié', 218230, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:2hpdKwumbBoIkq5zaoXVOu', 'Lead Me', 'Anthony Franciso, Naja Wilson', 192940, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:1FSqeugQ1A697oAv8EZ516', 'Can''t Believe It', 'Corey Wise, Tre''Gadd', 174249, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:2PVhk6KhiF4yKXFVCACZuG', 'Lay Down', 'Trip Lee', 171177, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:3GJpQY3I6YTgL3TtvvxmNm', 'All For You', 'Hulvey', 215088, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:0fPdM4EC9Fyh7Wk6SWVTht', 'leave it to God', 'nobigdyl.', 131932, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:5NsejBqTH83xlbKFdjScSw', 'Chasing Ghosts', 'Swoope, Lecrae', 204124, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:6NiEYy97bODtt7ntvUmlvp', 'IN MY ROOM', 'Marty, McKenna Johns', 173788, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:57sEnzGIfUU3BYAo8uvezv', '77 Times', 'Tre''Gadd', 210629, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:4DVgIpxVlwCGKP4fwgetWM', 'LUV HIGH', 'Gavin the HotRod', 124006, '{}'::text[], '{"rest"}'::text[], NULL, NULL);
INSERT INTO spotify_tracks (spotify_id, name, artist, duration_ms, genres, usage, hype_timestamp, skip_outro) VALUES ('spotify:track:10oQuQIQaOs6tExGsQnifs', 'Magic', 'Trip Lee, WHATUPRG', 230639, '{}'::text[], '{"rest"}'::text[], NULL, NULL);