import { NextResponse } from "next/server";
import { db } from "@acme/db/client";
import { exercises } from "@acme/db/schema";
import type { InferInsertModel } from "drizzle-orm";

const allExercises: InferInsertModel<typeof exercises>[] = [
  {
    name: "Barbell Bench Press",
    primaryMuscle: "chest" as const,
    secondaryMuscles: ["triceps", "shoulders"] as const,
    loadedJoints: ["shoulders"] as const,
    movementPattern: "horizontal_push" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "scapular_control"] as const,
    functionTags: ["foundational"] as const,
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["barbell", "bench"] as const,
    strengthLevel: "moderate" as const,
  },
  {
    name: "Dumbbell Press",
    primaryMuscle: "chest" as const,
    secondaryMuscles: ["triceps", "shoulders"] as const,
    loadedJoints: ["shoulders"] as const,
    movementPattern: "horizontal_push" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "scapular_control"] as const,
    functionTags: ["foundational"] as const,
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "low" as const,
    equipment: ["dumbbells", "bench"],
    strengthLevel: "low" as const,
  },
  {
    name: "Incline Dumbbell Press",
    primaryMuscle: "upper_chest" as const,
    secondaryMuscles: ["triceps", "shoulders"] as const,
    loadedJoints: ["shoulders"] as const,
    movementPattern: "horizontal_push" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "scapular_control"] as const,
    functionTags: ["foundational"] as const,
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "low" as const,
    equipment: ["dumbbells", "bench"],
    strengthLevel: "low" as const,
  },
  {
    name: "Dumbbell Bench Row",
    primaryMuscle: "lats" as const,
    secondaryMuscles: ["biceps", "upper_back"] as const,
    loadedJoints: [] as const,
    movementPattern: "horizontal_pull" as const,
    modality: "strength" as const,
    movementTags: ["unilateral", "scapular_control", "core_stability"] as const,
    functionTags: ["foundational", "rehab_friendly"] as const,
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["dumbbells", "bench"],
    strengthLevel: "low" as const,
  },
  {
    name: "Landmine T Bar Row",
    primaryMuscle: "lats" as const,
    secondaryMuscles: ["biceps", "upper_back"] as const,
    loadedJoints: [] as const,
    movementPattern: "horizontal_pull" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "scapular_control", "postural_control"] as const,
    functionTags: [] as const,
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "moderate" as const,
    equipment: ["barbell", "landmine"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "TRX Mid Row",
    primaryMuscle: "upper_back" as const,
    secondaryMuscles: ["biceps", "lats"],
    loadedJoints: [] as const,
    movementPattern: "horizontal_pull" as const,
    modality: "stability" as const,
    movementTags: ["bilateral", "scapular_control", "core_stability"] as const,
    functionTags: ["rehab_friendly"] as const,
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["trx"] as const,
    strengthLevel: "low" as const,
  },
  {
    name: "Dumbbell Pullover",
    primaryMuscle: "lats" as const,
    secondaryMuscles: ["chest", "triceps"] as const,
    loadedJoints: [] as const,
    movementPattern: "horizontal_pull" as const,
    modality: "strength" as const,
    movementTags: ["scapular_control", "core_stability", "bilateral"] as const,
    functionTags: [] as const,
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["dumbbells"] as const,
    strengthLevel: "moderate" as const,
  },
  {
    name: "Bent-Over Single Arm Kettlebell Row (Gorilla Row)",
    primaryMuscle: "lats" as const,
    secondaryMuscles: ["biceps", "upper_back"] as const,
    loadedJoints: [] as const,
    movementPattern: "horizontal_pull" as const,
    modality: "strength" as const,
    movementTags: ["unilateral", "scapular_control", "hip_dominant"] as const,
    functionTags: ["foundational"] as const,
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["kettlebell"] as const,
    strengthLevel: "low" as const,
  },
  {
    name: "Batwing Chest-Supported Row",
    primaryMuscle: "upper_back" as const,
    secondaryMuscles: ["lats", "biceps"] as const,
    loadedJoints: [] as const,
    movementPattern: "horizontal_pull" as const,
    modality: "strength" as const,
    movementTags: ["isometric_control", "scapular_control", "bilateral"] as const,
    functionTags: [] as const,
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["dumbbells", "bench"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Face Pulls",
    primaryMuscle: "delts" as const,
    secondaryMuscles: ["traps"] as const,
    loadedJoints: [] as const,
    movementPattern: "horizontal_pull" as const,
    modality: "stability" as const,
    movementTags: ["scapular_control", "bilateral"] as const,
    functionTags: ["rehab_friendly", "warmup_friendly"] as const,
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["cable_machine"] as const,
    strengthLevel: "low" as const,
  },
  {
    name: "Band Pull-Apart",
    primaryMuscle: "traps" as const,
    secondaryMuscles: ["delts"] as const,
    loadedJoints: [] as const,
    movementPattern: "horizontal_pull" as const,
    modality: "stability" as const,
    movementTags: ["bilateral", "scapular_control"] as const,
    functionTags: ["rehab_friendly", "warmup_friendly"] as const,
    fatigueProfile: "low_local" as const,
    complexityLevel: "very_low" as const,
    equipment: ["bands"] as const,
    strengthLevel: "very_low" as const,
  },
  {
    name: "Lateral Shoulder Raise",
    primaryMuscle: "delts" as const,
    secondaryMuscles: [] as const,
    loadedJoints: ["shoulders"] as const,
    movementPattern: "shoulder_isolation" as const,
    modality: "strength" as const,
    movementTags: ["bilateral"] as const,
    functionTags: [] as const,
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["dumbbells"] as const,
    strengthLevel: "low" as const,
  },
  {
    name: "Y/W Raises",
    primaryMuscle: "delts" as const,
    secondaryMuscles: [] as const,
    loadedJoints: [] as const,
    movementPattern: "vertical_push" as const,
    modality: "stability" as const,
    movementTags: ["scapular_control", "postural_control"] as const,
    functionTags: ["rehab_friendly", "warmup_friendly"] as const,
    fatigueProfile: "low_local" as const,
    complexityLevel: "moderate" as const,
    equipment: [] as const,
    strengthLevel: "very_low" as const,
  },
  {
    name: "Barbell Back Squat",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "hamstrings"] as const,
    loadedJoints: ["knees", "lower_back"] as const,
    movementPattern: "squat" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "knee_dominant", "postural_control"] as const,
    functionTags: ["foundational"] as const,
    fatigueProfile: "high_systemic" as const,
    complexityLevel: "moderate" as const,
    equipment: ["barbell"] as const,
    strengthLevel: "moderate" as const,
  },
  {
    name: "Goblet Squat",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "core"] as const,
    loadedJoints: ["knees", "hips"] as const,
    movementPattern: "squat" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "knee_dominant", "postural_control"] as const,
    functionTags: ["foundational", "warmup_friendly"] as const,
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "low" as const,
    equipment: ["dumbbells"] as const,
    strengthLevel: "low" as const,
  },
  {
    name: "Jump Squat",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "calves"] as const,
    loadedJoints: ["knees", "hips", "ankles"] as const,
    movementPattern: "squat" as const,
    modality: "power" as const,
    movementTags: ["bilateral", "knee_dominant", "explosive"] as const,
    functionTags: ["finisher_friendly"] as const,
    fatigueProfile: "metabolic" as const,
    complexityLevel: "moderate" as const,
    equipment: [] as const,
    strengthLevel: "moderate" as const,
  },
  {
    name: "Lunge with Biceps Curl",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "biceps"] as const,
    loadedJoints: ["knees", "hips"] as const,
    movementPattern: "lunge" as const,
    modality: "strength" as const,
    movementTags: ["unilateral", "knee_dominant", "balance_challenge"] as const,
    functionTags: [] as const,
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "moderate" as const,
    equipment: ["dumbbells"] as const,
    strengthLevel: "moderate" as const,
  },
  {
    name: "Lateral Step-Up with Goblet Hold",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "core"] as const,
    loadedJoints: ["knees", "hips"] as const,
    movementPattern: "lunge" as const,
    modality: "strength" as const,
    movementTags: ["unilateral", "knee_dominant", "balance_challenge"] as const,
    functionTags: [] as const,
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "moderate" as const,
    equipment: ["box", "dumbbells"] as const,
    strengthLevel: "moderate" as const,
  },
  {
    name: "Farmer's Carry Step-Up",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "core"] as const,
    loadedJoints: ["knees"] as const,
    movementPattern: "lunge" as const,
    modality: "conditioning" as const,
    movementTags: ["unilateral", "knee_dominant", "balance_challenge"] as const,
    functionTags: [] as const,
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "moderate" as const,
    equipment: ["box", "dumbbells"] as const,
    strengthLevel: "moderate" as const,
  },
  {
    name: "Farmer's Carry",
    primaryMuscle: "core" as const,
    secondaryMuscles: ["traps"] as const,
    loadedJoints: [] as const,
    movementPattern: "carry" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "postural_control", "core_stability"] as const,
    functionTags: ["foundational"] as const,
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "low" as const,
    equipment: ["dumbbells"] as const,
    strengthLevel: "low" as const,
  },
  {
    name: "Glute Bridge Thrust with Dumbbell",
    primaryMuscle: "glutes" as const,
    secondaryMuscles: ["hamstrings", "core"] as const,
    loadedJoints: [] as const,
    movementPattern: "hinge" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "hip_dominant"] as const,
    functionTags: ["rehab_friendly"] as const,
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["dumbbells"] as const,
    strengthLevel: "low" as const,
  },
  {
    name: "Nordic Hamstring Curl",
    primaryMuscle: "hamstrings" as const,
    secondaryMuscles: ["glutes"] as const,
    loadedJoints: ["knees"] as const,
    movementPattern: "leg_isolation" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "knee_dominant"] as const,
    functionTags: [] as const,
    fatigueProfile: "high_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["dumbbells"] as const,
    strengthLevel: "high" as const,
  },
  {
    name: "BOSU Hamstring Curl",
    primaryMuscle: "hamstrings" as const,
    secondaryMuscles: ["glutes"] as const,
    loadedJoints: ["knees"] as const,
    movementPattern: "leg_isolation" as const,
    modality: "stability" as const,
    movementTags: ["bilateral", "knee_dominant", "balance_challenge"] as const,
    functionTags: ["rehab_friendly"] as const,
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["bosu_ball", "dumbbells"] as const,
    strengthLevel: "high" as const,
  },
  {
    name: "Dead Bug",
    primaryMuscle: "core" as const,
    secondaryMuscles: [] as const,
    loadedJoints: [] as const,
    movementPattern: "core" as const,
    modality: "core" as const,
    movementTags: ["core_stability", "anti_rotation", "isometric_control"] as const,
    functionTags: ["rehab_friendly", "warmup_friendly"] as const,
    fatigueProfile: "low_local" as const,
    complexityLevel: "low" as const,
    equipment: [] as const,
    strengthLevel: "low" as const,
  },
  {
    name: "Stir-the-Pot Plank",
    primaryMuscle: "core" as const,
    secondaryMuscles: ["shoulders"] as const,
    loadedJoints: [] as const,
    movementPattern: "core" as const,
    modality: "core" as const,
    movementTags: ["core_stability", "isometric_control", "anti_rotation"] as const,
    functionTags: [] as const,
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["swiss_ball"] as const,
    strengthLevel: "moderate" as const,
  },
  {
    name: "Banded Prone Overhead Press",
    primaryMuscle: "core" as const,
    secondaryMuscles: ["shoulders"] as const,
    loadedJoints: [] as const,
    movementPattern: "vertical_push" as const,
    modality: "mobility" as const,
    movementTags: ["scapular_control", "postural_control"] as const,
    functionTags: ["rehab_friendly", "warmup_friendly"] as const,
    fatigueProfile: "low_local" as const,
    complexityLevel: "low" as const,
    equipment: ["bands"] as const,
    strengthLevel: "low" as const,
  },
  {
    name: "Swiss Ball Forearm Plank",
    primaryMuscle: "core" as const,
    secondaryMuscles: ["shoulders"] as const,
    loadedJoints: [] as const,
    movementPattern: "core" as const,
    modality: "core" as const,
    movementTags: ["core_stability", "isometric_control", "balance_challenge"] as const,
    functionTags: ["rehab_friendly"] as const,
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "very_low" as const,
    equipment: ["swiss_ball"] as const,
    strengthLevel: "moderate" as const,
  },
  {
    name: "Monster Walk (Banded Lateral Walk)",
    primaryMuscle: "abductors" as const,
    secondaryMuscles: ["glutes"] as const,
    loadedJoints: [] as const,
    movementPattern: "leg_isolation" as const,
    modality: "stability" as const,
    movementTags: ["hip_stability"] as const,
    functionTags: ["rehab_friendly", "warmup_friendly"] as const,
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["bands"] as const,
    strengthLevel: "low" as const,
  },
  {
    name: "Quadruped Fire Hydrant (Peeing Dog)",
    primaryMuscle: "abductors" as const,
    secondaryMuscles: ["glutes", "core"] as const,
    loadedJoints: [] as const,
    movementPattern: "leg_isolation" as const,
    modality: "stability" as const,
    movementTags: ["hip_stability", "end_range_control", "unilateral"] as const,
    functionTags: ["rehab_friendly", "warmup_friendly"] as const,
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["bands"] as const,
    strengthLevel: "low" as const,
  },
  {
    name: "Medicine Ball Slam",
    primaryMuscle: "core" as const,
    secondaryMuscles: ["shoulders", "lats"] as const,
    loadedJoints: [] as const,
    movementPattern: "core" as const,
    modality: "power" as const,
    movementTags: ["explosive", "hip_dominant"] as const,
    functionTags: ["finisher_friendly"] as const,
    fatigueProfile: "metabolic" as const,
    complexityLevel: "low" as const,
    equipment: ["med_ball"] as const,
    strengthLevel: "low" as const,
  },
  {
    name: "Plank Up-Down (Elbow to Hand)",
    primaryMuscle: "core" as const,
    secondaryMuscles: ["shoulders", "triceps"] as const,
    loadedJoints: [] as const,
    movementPattern: "core" as const,
    modality: "core" as const,
    movementTags: ["core_stability", "postural_control"] as const,
    functionTags: ["warmup_friendly"] as const,
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: [] as const,
    strengthLevel: "low" as const,
  },
  {
    name: "Australian Pull-Up",
    primaryMuscle: "upper_back" as const,
    secondaryMuscles: ["biceps", "lats"] as const,
    loadedJoints: ["shoulders"] as const,
    movementPattern: "vertical_pull" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "scapular_control"] as const,
    functionTags: ["foundational"] as const,
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["barbell"] as const,
    strengthLevel: "low" as const,
  },
  {
    name: "Straight-Arm Pull-Down",
    primaryMuscle: "lats" as const,
    secondaryMuscles: ["triceps", "core"] as const,
    loadedJoints: ["shoulders"] as const,
    movementPattern: "vertical_pull" as const,
    modality: "strength" as const,
    movementTags: ["scapular_control"] as const,
    functionTags: [] as const,
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["cable_machine"] as const,
    strengthLevel: "low" as const,
  },
  {
    name: "Dumbbell Bent-Over Reverse Fly",
    primaryMuscle: "delts" as const,
    secondaryMuscles: ["traps", "upper_back"] as const,
    loadedJoints: ["shoulders"] as const,
    movementPattern: "horizontal_pull" as const,
    modality: "strength" as const,
    movementTags: ["scapular_control", "postural_control"] as const,
    functionTags: [] as const,
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["dumbbells"] as const,
    strengthLevel: "low" as const,
  },
  {
    name: "Side Plank Press-Out",
    primaryMuscle: "core" as const,
    secondaryMuscles: ["shoulders"],
    loadedJoints: ["shoulders"],
    movementPattern: "core" as const,
    modality: "core" as const,
    movementTags: ["anti_rotation", "core_stability"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["dumbbells"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Cable Low-to-High Chest Fly",
    primaryMuscle: "upper_chest" as const,
    secondaryMuscles: ["shoulders", "core"],
    loadedJoints: ["shoulders"],
    movementPattern: "horizontal_push" as const,
    modality: "strength" as const,
    movementTags: [],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["cable_machine"],
    strengthLevel: "low" as const,
  },
  {
    name: "Cable Side Plank Row",
    primaryMuscle: "lats" as const,
    secondaryMuscles: ["core", "biceps"],
    loadedJoints: ["shoulders"],
    movementPattern: "horizontal_pull" as const,
    modality: "core" as const,
    movementTags: ["anti_rotation", "core_stability", "unilateral"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["cable_machine"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Curtsy Lunge",
    primaryMuscle: "glutes" as const,
    secondaryMuscles: ["quads", "adductors"],
    loadedJoints: ["knees", "hips"],
    movementPattern: "lunge" as const,
    modality: "strength" as const,
    movementTags: ["cross_plane", "unilateral", "hip_stability"],
    functionTags: [],
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "moderate" as const,
    equipment: ["dumbbells"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Side Plank Reverse Fly",
    primaryMuscle: "delts" as const,
    secondaryMuscles: ["core", "upper_back"],
    loadedJoints: ["shoulders"],
    movementPattern: "horizontal_pull" as const,
    modality: "core" as const,
    movementTags: ["unilateral", "scapular_control", "core_stability"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["dumbbells"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Landmine Shoulder Press",
    primaryMuscle: "shoulders" as const,
    secondaryMuscles: ["triceps", "core"],
    loadedJoints: ["shoulders"],
    movementPattern: "vertical_push" as const,
    modality: "strength" as const,
    movementTags: ["unilateral", "postural_control"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["landmine", "barbell"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Landmine Shoulder-to-Shoulder Press",
    primaryMuscle: "shoulders" as const,
    secondaryMuscles: ["triceps", "core"],
    loadedJoints: ["shoulders"],
    movementPattern: "vertical_push" as const,
    modality: "power" as const,
    movementTags: ["unilateral", "postural_control", "rotational"],
    functionTags: [],
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "high" as const,
    equipment: ["landmine", "barbell"],
    strengthLevel: "high" as const,
  },
  {
    name: "Landmine Reverse Lunge",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "core"],
    loadedJoints: ["hips", "knees"],
    movementPattern: "lunge" as const,
    modality: "strength" as const,
    movementTags: ["unilateral", "hip_stability", "postural_control"],
    functionTags: [],
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "moderate" as const,
    equipment: ["landmine", "barbell"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Offset Lateral Lunge",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "adductors"],
    loadedJoints: ["hips", "knees"],
    movementPattern: "lunge" as const,
    modality: "strength" as const,
    movementTags: ["unilateral", "hip_stability", "balance_challenge"],
    functionTags: [],
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "moderate" as const,
    equipment: ["dumbbells"],
    strengthLevel: "low" as const,
  },
  {
    name: "Lateral Lunge",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "adductors"],
    loadedJoints: ["knees"],
    movementPattern: "lunge" as const,
    modality: "strength" as const,
    movementTags: ["unilateral", "hip_stability", "balance_challenge"],
    functionTags: ["foundational"],
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "moderate" as const,
    equipment: ["dumbbells"],
    strengthLevel: "low" as const,
  },
  {
    name: "Pull-Ups",
    primaryMuscle: "lats" as const,
    secondaryMuscles: ["biceps", "upper_back"],
    loadedJoints: ["shoulders"],
    movementPattern: "vertical_pull" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "scapular_control"],
    functionTags: ["foundational"],
    fatigueProfile: "high_local" as const,
    complexityLevel: "high" as const,
    equipment: ["pull_up_bar"],
    strengthLevel: "high" as const,
  },
  {
    name: "Single-Arm Cable Row",
    primaryMuscle: "lats" as const,
    secondaryMuscles: ["biceps", "upper_back"],
    loadedJoints: ["shoulders"],
    movementPattern: "horizontal_pull" as const,
    modality: "strength" as const,
    movementTags: ["unilateral", "scapular_control", "core_stability"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["cable_machine"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Russian Twist",
    primaryMuscle: "obliques" as const,
    secondaryMuscles: ["core"],
    loadedJoints: [],
    movementPattern: "core" as const,
    modality: "core" as const,
    movementTags: ["rotational", "core_stability"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: [],
    strengthLevel: "low" as const,
  },
  {
    name: "Cable Chest Press (variations)",
    primaryMuscle: "chest" as const,
    secondaryMuscles: ["shoulders", "triceps"],
    loadedJoints: ["shoulders"],
    movementPattern: "horizontal_push" as const,
    modality: "strength" as const,
    movementTags: [],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["cable_machine"],
    strengthLevel: "low" as const,
  },
  {
    name: "Face Pull to Overhead Press",
    primaryMuscle: "shoulders" as const,
    secondaryMuscles: ["traps", "upper_back"],
    loadedJoints: ["shoulders"],
    movementPattern: "horizontal_pull" as const,
    modality: "stability" as const,
    movementTags: ["scapular_control", "postural_control", "bilateral"],
    functionTags: ["warmup_friendly"],
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "moderate" as const,
    equipment: ["cable_machine"],
    strengthLevel: "low" as const,
  },
  {
    name: "Farmer's Carry Reverse Lunge",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "core"],
    loadedJoints: ["knees"],
    movementPattern: "lunge" as const,
    modality: "strength" as const,
    movementTags: ["unilateral", "postural_control", "hip_stability"],
    functionTags: ["foundational"],
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "moderate" as const,
    equipment: ["dumbbells"],
    strengthLevel: "low" as const,
  },
  {
    name: "Side Plank Hip Raise",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "core"],
    loadedJoints: [],
    movementPattern: "core" as const,
    modality: "core" as const,
    movementTags: ["core_stability", "isometric_control", "hip_stability"],
    functionTags: ["rehab_friendly", "warmup_friendly"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: [],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Incline Bicep Curl",
    primaryMuscle: "biceps" as const,
    secondaryMuscles: [],
    loadedJoints: [],
    movementPattern: "arm_isolation" as const,
    modality: "strength" as const,
    movementTags: ["bilateral"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["dumbbells", "bench"],
    strengthLevel: "low" as const,
  },
  {
    name: "Suitcase Kettlebell Lunge",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "core"],
    loadedJoints: ["knees"],
    movementPattern: "lunge" as const,
    modality: "strength" as const,
    movementTags: ["unilateral", "anti_rotation", "hip_stability"],
    functionTags: [],
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "moderate" as const,
    equipment: ["kettlebell"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Plank Jack",
    primaryMuscle: "core" as const,
    secondaryMuscles: ["shoulders", "glutes"],
    loadedJoints: [],
    movementPattern: "core" as const,
    modality: "conditioning" as const,
    movementTags: ["core_stability", "explosive"],
    functionTags: ["warmup_friendly"],
    fatigueProfile: "metabolic" as const,
    complexityLevel: "low" as const,
    equipment: [],
    strengthLevel: "low" as const,
  },
  {
    name: "Bosu Plank Jack",
    primaryMuscle: "core" as const,
    secondaryMuscles: ["shoulders", "glutes"],
    loadedJoints: [],
    movementPattern: "core" as const,
    modality: "conditioning" as const,
    movementTags: ["core_stability", "explosive", "balance_challenge"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["bosu_ball"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Bodyweight Triceps Extension",
    primaryMuscle: "triceps" as const,
    secondaryMuscles: ["shoulders"],
    loadedJoints: [],
    movementPattern: "arm_isolation" as const,
    modality: "strength" as const,
    movementTags: ["bilateral"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: [],
    strengthLevel: "low" as const,
  },
  {
    name: "Skull Crusher",
    primaryMuscle: "triceps" as const,
    secondaryMuscles: [],
    loadedJoints: ["elbows"],
    movementPattern: "arm_isolation" as const,
    modality: "strength" as const,
    movementTags: ["bilateral"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["dumbbells"],
    strengthLevel: "low" as const,
  },
  {
    name: "Incline Shoulder Raises (three-ways)",
    primaryMuscle: "delts" as const,
    secondaryMuscles: ["traps"],
    loadedJoints: ["shoulders"],
    movementPattern: "shoulder_isolation" as const,
    modality: "strength" as const,
    movementTags: ["bilateral"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["dumbbells"],
    strengthLevel: "low" as const,
  },
  {
    name: "Incline Barbell Bench Press",
    primaryMuscle: "upper_chest" as const,
    secondaryMuscles: ["shoulders", "triceps"],
    loadedJoints: ["shoulders"],
    movementPattern: "horizontal_push" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "scapular_control"],
    functionTags: ["foundational"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["barbell", "bench"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Goblet Squat Pulse",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "core"],
    loadedJoints: ["knees", "hips"],
    movementPattern: "squat" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "knee_dominant"],
    functionTags: ["warmup_friendly"],
    fatigueProfile: "metabolic" as const,
    complexityLevel: "low" as const,
    equipment: ["dumbbells"],
    strengthLevel: "low" as const,
  },
  {
    name: "Single-Leg Glute Bridge with Band",
    primaryMuscle: "glutes" as const,
    secondaryMuscles: ["hamstrings", "core"],
    loadedJoints: [],
    movementPattern: "hinge" as const,
    modality: "stability" as const,
    movementTags: ["unilateral", "hip_dominant", "hip_stability"],
    functionTags: ["rehab_friendly", "warmup_friendly"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["bands"],
    strengthLevel: "low" as const,
  },
  {
    name: "Dumbbell Thruster",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["shoulders", "glutes"],
    loadedJoints: ["shoulders", "knees"],
    movementPattern: "squat" as const,
    modality: "conditioning" as const,
    movementTags: ["bilateral", "knee_dominant", "explosive"],
    functionTags: ["finisher_friendly"],
    fatigueProfile: "metabolic" as const,
    complexityLevel: "moderate" as const,
    equipment: ["dumbbells"],
    strengthLevel: "low" as const,
  },
  {
    name: "Dumbbell Hammer Curls",
    primaryMuscle: "biceps" as const,
    secondaryMuscles: [],
    loadedJoints: [],
    movementPattern: "arm_isolation" as const,
    modality: "strength" as const,
    movementTags: ["bilateral"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "very_low" as const,
    equipment: ["dumbbells"],
    strengthLevel: "low" as const,
  },
  {
    name: "Dumbbell Overhead Tricep Extension",
    primaryMuscle: "triceps" as const,
    secondaryMuscles: ["shoulders"],
    loadedJoints: ["elbows", "shoulders"],
    movementPattern: "arm_isolation" as const,
    modality: "strength" as const,
    movementTags: ["bilateral"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["dumbbells"],
    strengthLevel: "low" as const,
  },
  {
    name: "Rope Tricep Pressdown",
    primaryMuscle: "triceps" as const,
    secondaryMuscles: [],
    loadedJoints: [],
    movementPattern: "arm_isolation" as const,
    modality: "strength" as const,
    movementTags: ["bilateral"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["cable_machine"],
    strengthLevel: "low" as const,
  },
  {
    name: "Pull-Ups (assisted with bands)",
    primaryMuscle: "lats" as const,
    secondaryMuscles: ["biceps", "upper_back"],
    loadedJoints: ["shoulders"],
    movementPattern: "vertical_pull" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "scapular_control"],
    functionTags: ["foundational"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["pull_up_bar"],
    strengthLevel: "low" as const,
  },
  {
    name: "TRX Y Raise",
    primaryMuscle: "traps" as const,
    secondaryMuscles: ["delts", "upper_back"],
    loadedJoints: ["shoulders"],
    movementPattern: "shoulder_isolation" as const,
    modality: "stability" as const,
    movementTags: ["scapular_control", "postural_control", "bilateral"],
    functionTags: ["rehab_friendly", "warmup_friendly"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["trx"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Single-Arm Kettlebell Suitcase Carry",
    primaryMuscle: "core" as const,
    secondaryMuscles: ["obliques", "traps"],
    loadedJoints: [],
    movementPattern: "carry" as const,
    modality: "stability" as const,
    movementTags: ["unilateral", "anti_rotation", "postural_control"],
    functionTags: ["foundational"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["kettlebell"],
    strengthLevel: "low" as const,
  },
  {
    name: "Lat Pulldown",
    primaryMuscle: "lats" as const,
    secondaryMuscles: ["biceps", "upper_back"],
    loadedJoints: ["shoulders"],
    movementPattern: "vertical_pull" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "scapular_control"],
    functionTags: ["foundational"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["back_machine"],
    strengthLevel: "low" as const,
  },
  {
    name: "Bear Crawl (Forward and Back)",
    primaryMuscle: "core" as const,
    secondaryMuscles: ["shoulders", "quads"],
    loadedJoints: [],
    movementPattern: "core" as const,
    modality: "core" as const,
    movementTags: ["core_stability", "postural_control"],
    functionTags: ["warmup_friendly"],
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "moderate" as const,
    equipment: [],
    strengthLevel: "low" as const,
  },
  {
    name: "In-and-Out Squat Jumps",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "calves"],
    loadedJoints: ["knees"],
    movementPattern: "squat" as const,
    modality: "conditioning" as const,
    movementTags: ["bilateral", "explosive", "knee_dominant"],
    functionTags: ["finisher_friendly"],
    fatigueProfile: "metabolic" as const,
    complexityLevel: "moderate" as const,
    equipment: [],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Box Pike Walkout",
    primaryMuscle: "core" as const,
    secondaryMuscles: ["shoulders", "hamstrings"],
    loadedJoints: [],
    movementPattern: "hinge" as const,
    modality: "core" as const,
    movementTags: ["core_stability"],
    functionTags: ["warmup_friendly"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["bench"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Band-Assisted Push-Ups",
    primaryMuscle: "chest" as const,
    secondaryMuscles: ["triceps", "shoulders"],
    loadedJoints: ["shoulders"],
    movementPattern: "horizontal_push" as const,
    modality: "strength" as const,
    movementTags: ["bilateral"],
    functionTags: ["foundational"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["bands"],
    strengthLevel: "low" as const,
  },
  {
    name: "Alternating Isometric Dumbbell Curl Hold",
    primaryMuscle: "biceps" as const,
    secondaryMuscles: [],
    loadedJoints: [],
    movementPattern: "arm_isolation" as const,
    modality: "strength" as const,
    movementTags: ["unilateral", "isometric_control"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["dumbbells"],
    strengthLevel: "low" as const,
  },
  {
    name: "Box Pistol Squat",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "hamstrings"],
    loadedJoints: ["knees"],
    movementPattern: "squat" as const,
    modality: "strength" as const,
    movementTags: ["unilateral", "balance_challenge", "hip_dominant"],
    functionTags: [],
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "high" as const,
    equipment: ["bench"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Elevated Calf Raises",
    primaryMuscle: "calves" as const,
    secondaryMuscles: [],
    loadedJoints: ["ankles"],
    movementPattern: "leg_isolation" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "end_range_control"],
    functionTags: ["rehab_friendly", "warmup_friendly"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "very_low" as const,
    equipment: [],
    strengthLevel: "low" as const,
  },
  {
    name: "Anterior Tibialis Raises",
    primaryMuscle: "shins" as const,
    secondaryMuscles: [],
    loadedJoints: ["ankles"],
    movementPattern: "leg_isolation" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "end_range_control"],
    functionTags: ["rehab_friendly", "warmup_friendly"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "very_low" as const,
    equipment: [],
    strengthLevel: "low" as const,
  },
  {
    name: "Plank Reach",
    primaryMuscle: "core" as const,
    secondaryMuscles: ["shoulders"],
    loadedJoints: [],
    movementPattern: "core" as const,
    modality: "core" as const,
    movementTags: ["core_stability", "isometric_control", "anti_rotation"],
    functionTags: ["warmup_friendly", "rehab_friendly"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: [],
    strengthLevel: "low" as const,
  },
  {
    name: "Goblet Pause Squat (3 Seconds)",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "core"],
    loadedJoints: ["knees", "hips"],
    movementPattern: "squat" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "knee_dominant", "isometric_control"],
    functionTags: ["foundational", "mobility_focus", "warmup_friendly"],
    fatigueProfile: "metabolic" as const,
    complexityLevel: "low" as const,
    equipment: ["dumbbells"],
    strengthLevel: "low" as const,
  },
  {
    name: "Flutter Kicks",
    primaryMuscle: "core" as const,
    secondaryMuscles: [],
    loadedJoints: [],
    movementPattern: "core" as const,
    modality: "core" as const,
    movementTags: ["core_stability", "isometric_control"],
    functionTags: ["finisher_friendly"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: [],
    strengthLevel: "low" as const,
  },
  {
    name: "Bulgarian Split Squat",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "hamstrings"],
    loadedJoints: ["knees", "hips"],
    movementPattern: "lunge" as const,
    modality: "strength" as const,
    movementTags: ["unilateral", "knee_dominant"],
    functionTags: ["foundational"],
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "moderate" as const,
    equipment: ["bench", "dumbbells"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Bulgarian Squat Jumps",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "calves"],
    loadedJoints: ["knees", "hips", "ankles"],
    movementPattern: "lunge" as const,
    modality: "power" as const,
    movementTags: ["unilateral", "knee_dominant", "explosive"],
    functionTags: ["finisher_friendly"],
    fatigueProfile: "metabolic" as const,
    complexityLevel: "high" as const,
    equipment: ["bench", "dumbbells"],
    strengthLevel: "high" as const,
  },
  {
    name: "Box Jumps",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "calves"],
    loadedJoints: ["knees", "hips", "ankles"],
    movementPattern: "squat" as const,
    modality: "power" as const,
    movementTags: ["bilateral", "explosive"],
    functionTags: ["finisher_friendly"],
    fatigueProfile: "high_systemic" as const,
    complexityLevel: "moderate" as const,
    equipment: ["box"],
    strengthLevel: "high" as const,
  },
  {
    name: "3-Point Dumbbell Row",
    primaryMuscle: "lats" as const,
    secondaryMuscles: ["biceps"],
    loadedJoints: ["shoulders"],
    movementPattern: "horizontal_pull" as const,
    modality: "strength" as const,
    movementTags: ["unilateral", "scapular_control"],
    functionTags: ["foundational"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["dumbbells"],
    strengthLevel: "low" as const,
  },
  {
    name: "Dragon Flag",
    primaryMuscle: "core" as const,
    secondaryMuscles: [],
    loadedJoints: ["lower_back"],
    movementPattern: "core" as const,
    modality: "core" as const,
    movementTags: ["core_stability", "isometric_control"],
    functionTags: [],
    fatigueProfile: "high_local" as const,
    complexityLevel: "high" as const,
    equipment: ["bench"],
    strengthLevel: "high" as const,
  },
  {
    name: "Hollow Body One-Arm Press",
    primaryMuscle: "chest" as const,
    secondaryMuscles: ["core", "shoulders"],
    loadedJoints: ["shoulders"],
    movementPattern: "core" as const,
    modality: "core" as const,
    movementTags: ["anti_rotation", "core_stability", "postural_control"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["bench"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Alternating Incline Dumbbell Chest Press",
    primaryMuscle: "chest" as const,
    secondaryMuscles: ["shoulders", "triceps"],
    loadedJoints: ["shoulders"],
    movementPattern: "horizontal_push" as const,
    modality: "strength" as const,
    movementTags: ["unilateral"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["bench"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Glute Kickbacks",
    primaryMuscle: "glutes" as const,
    secondaryMuscles: ["hamstrings", "core"],
    loadedJoints: [],
    movementPattern: "leg_isolation" as const,
    modality: "strength" as const,
    movementTags: ["unilateral", "hip_dominant", "hip_stability"],
    functionTags: ["rehab_friendly"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "very_low" as const,
    equipment: [],
    strengthLevel: "low" as const,
  },
  {
    name: "Deadlift",
    primaryMuscle: "hamstrings" as const,
    secondaryMuscles: ["glutes", "lower_back"],
    loadedJoints: ["hips", "knees", "lower_back"],
    movementPattern: "hinge" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "hip_dominant", "postural_control"],
    functionTags: ["foundational"],
    fatigueProfile: "high_systemic" as const,
    complexityLevel: "moderate" as const,
    equipment: ["platform", "barbell"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Kettlebell Bottoms-Up Press",
    primaryMuscle: "shoulders" as const,
    secondaryMuscles: ["triceps", "core"],
    loadedJoints: ["shoulders", "wrists"],
    movementPattern: "vertical_push" as const,
    modality: "stability" as const,
    movementTags: ["unilateral", "postural_control", "scapular_control"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "high" as const,
    equipment: ["kettlebell"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Dumbbell Shoulder Press",
    primaryMuscle: "shoulders" as const,
    secondaryMuscles: ["triceps", "upper_chest"],
    loadedJoints: ["shoulders"],
    movementPattern: "vertical_push" as const,
    modality: "strength" as const,
    movementTags: ["bilateral"],
    functionTags: ["foundational"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["dumbbells"],
    strengthLevel: "low" as const,
  },
  {
    name: "TRX Bicep Curls",
    primaryMuscle: "biceps" as const,
    secondaryMuscles: [],
    loadedJoints: [],
    movementPattern: "arm_isolation" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "scapular_control"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["trx"],
    strengthLevel: "low" as const,
  },
  {
    name: "Ab Wheel Rollout",
    primaryMuscle: "core" as const,
    secondaryMuscles: ["lats"],
    loadedJoints: ["lower_back"],
    movementPattern: "core" as const,
    modality: "core" as const,
    movementTags: ["core_stability", "anti_rotation"],
    functionTags: [],
    fatigueProfile: "high_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["ab_wheel"],
    strengthLevel: "high" as const,
  },
  {
    name: "Single-Arm Shoulder Press",
    primaryMuscle: "shoulders" as const,
    secondaryMuscles: ["triceps", "core"],
    loadedJoints: ["shoulders"],
    movementPattern: "vertical_push" as const,
    modality: "strength" as const,
    movementTags: ["unilateral", "postural_control"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["dumbbells"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Archer Push-Ups",
    primaryMuscle: "chest" as const,
    secondaryMuscles: ["triceps", "shoulders"],
    loadedJoints: ["shoulders"],
    movementPattern: "horizontal_push" as const,
    modality: "strength" as const,
    movementTags: ["unilateral"],
    functionTags: [],
    fatigueProfile: "high_local" as const,
    complexityLevel: "high" as const,
    equipment: [],
    strengthLevel: "high" as const,
  },
  {
    name: "Copenhagen Plank",
    primaryMuscle: "adductors" as const,
    secondaryMuscles: ["obliques", "core"],
    loadedJoints: [],
    movementPattern: "core" as const,
    modality: "core" as const,
    movementTags: ["isometric_control", "hip_stability", "core_stability"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["bench"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Plank with Weight Drag",
    primaryMuscle: "core" as const,
    secondaryMuscles: ["shoulders", "obliques"],
    loadedJoints: [],
    movementPattern: "core" as const,
    modality: "core" as const,
    movementTags: ["core_stability", "anti_rotation"],
    functionTags: ["warmup_friendly"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["dumbbells"],
    strengthLevel: "low" as const,
  },
  {
    name: "Two-Arm Cable Row",
    primaryMuscle: "lats" as const,
    secondaryMuscles: ["biceps", "upper_back"],
    loadedJoints: ["shoulders"],
    movementPattern: "horizontal_pull" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "scapular_control"],
    functionTags: ["foundational"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["back_machine"],
    strengthLevel: "low" as const,
  },
  {
    name: "Push-Ups",
    primaryMuscle: "chest" as const,
    secondaryMuscles: ["triceps", "shoulders"],
    loadedJoints: ["shoulders"],
    movementPattern: "horizontal_push" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "scapular_control"],
    functionTags: ["foundational"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: [],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Elevated Push-Ups",
    primaryMuscle: "chest" as const,
    secondaryMuscles: ["triceps", "shoulders"],
    loadedJoints: ["shoulders", "wrists"],
    movementPattern: "horizontal_push" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "scapular_control"],
    functionTags: ["warmup_friendly"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["dumbbells"],
    strengthLevel: "low" as const,
  },
  {
    name: "Bird Dog Row",
    primaryMuscle: "lats" as const,
    secondaryMuscles: ["core", "upper_back"],
    loadedJoints: [],
    movementPattern: "horizontal_pull" as const,
    modality: "stability" as const,
    movementTags: ["unilateral", "core_stability", "anti_rotation"],
    functionTags: ["rehab_friendly", "warmup_friendly"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["dumbbells"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Barbell Glute Bridge on Bench",
    primaryMuscle: "glutes" as const,
    secondaryMuscles: ["hamstrings", "core"],
    loadedJoints: ["hips"],
    movementPattern: "hinge" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "hip_dominant"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["barbell", "bench"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Hollow Body Dumbbell Press",
    primaryMuscle: "chest" as const,
    secondaryMuscles: ["core", "shoulders"],
    loadedJoints: ["shoulders"],
    movementPattern: "core" as const,
    modality: "strength" as const,
    movementTags: ["core_stability", "anti_rotation", "postural_control"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["dumbbells"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Wall Squat Hold",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "core"],
    loadedJoints: ["knees", "hips"],
    movementPattern: "squat" as const,
    modality: "stability" as const,
    movementTags: ["isometric_control", "knee_dominant"],
    functionTags: [],
    fatigueProfile: "metabolic" as const,
    complexityLevel: "low" as const,
    equipment: [],
    strengthLevel: "low" as const,
  },
  {
    name: "Single-Leg Banded Kettlebell Suitcase Hold",
    primaryMuscle: "core" as const,
    secondaryMuscles: ["glutes", "obliques"],
    loadedJoints: ["ankles", "hips"],
    movementPattern: "core" as const,
    modality: "stability" as const,
    movementTags: ["unilateral", "balance_challenge", "anti_rotation"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["kettlebell"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Single-Leg Calf Raise",
    primaryMuscle: "calves" as const,
    secondaryMuscles: [],
    loadedJoints: ["ankles"],
    movementPattern: "leg_isolation" as const,
    modality: "strength" as const,
    movementTags: ["unilateral", "balance_challenge"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: [],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Banded Side Plank Clamshell",
    primaryMuscle: "abductors" as const,
    secondaryMuscles: ["glutes", "obliques"],
    loadedJoints: [],
    movementPattern: "core" as const,
    modality: "core" as const,
    movementTags: ["core_stability", "hip_stability", "anti_rotation"],
    functionTags: ["rehab_friendly"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["bands"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Single-Arm Kettlebell Overhead Press",
    primaryMuscle: "shoulders" as const,
    secondaryMuscles: ["triceps", "core"],
    loadedJoints: ["shoulders"],
    movementPattern: "vertical_push" as const,
    modality: "strength" as const,
    movementTags: ["unilateral", "postural_control", "anti_rotation"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["kettlebell"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Hanging Knee Raise",
    primaryMuscle: "core" as const,
    secondaryMuscles: [],
    loadedJoints: [],
    movementPattern: "core" as const,
    modality: "core" as const,
    movementTags: ["core_stability", "hip_dominant"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["pull_up_bar"],
    strengthLevel: "low" as const,
  },
  {
    name: "Diamond Push-Ups",
    primaryMuscle: "triceps" as const,
    secondaryMuscles: ["chest", "shoulders"],
    loadedJoints: ["shoulders"],
    movementPattern: "horizontal_push" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "scapular_control"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: [],
    strengthLevel: "moderate" as const,
  },
  {
    name: "BOSU Bird Dog",
    primaryMuscle: "core" as const,
    secondaryMuscles: ["glutes", "shoulders"],
    loadedJoints: [],
    movementPattern: "core" as const,
    modality: "stability" as const,
    movementTags: ["balance_challenge", "core_stability"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["bosu_ball"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Plank",
    primaryMuscle: "core" as const,
    secondaryMuscles: ["shoulders"],
    loadedJoints: [],
    movementPattern: "core" as const,
    modality: "core" as const,
    movementTags: ["isometric_control", "core_stability"],
    functionTags: ["rehab_friendly", "warmup_friendly"],
    fatigueProfile: "low_local" as const,
    complexityLevel: "very_low" as const,
    equipment: [],
    strengthLevel: "low" as const,
  },
  {
    name: "Renegade Row",
    primaryMuscle: "lats" as const,
    secondaryMuscles: ["core", "biceps"],
    loadedJoints: ["shoulders"],
    movementPattern: "horizontal_pull" as const,
    modality: "core" as const,
    movementTags: ["unilateral", "anti_rotation", "core_stability"],
    functionTags: [],
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "moderate" as const,
    equipment: ["dumbbells"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Pendlay Row",
    primaryMuscle: "lats" as const,
    secondaryMuscles: ["upper_back", "biceps"],
    loadedJoints: [],
    movementPattern: "horizontal_pull" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "scapular_control"],
    functionTags: ["foundational"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["barbell"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Twisting Pistons",
    primaryMuscle: "core" as const,
    secondaryMuscles: ["obliques", "shoulders"],
    loadedJoints: [],
    movementPattern: "core" as const,
    modality: "conditioning" as const,
    movementTags: ["rotational", "core_stability"],
    functionTags: ["finisher_friendly"],
    fatigueProfile: "metabolic" as const,
    complexityLevel: "moderate" as const,
    equipment: [],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Pistol Squat",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "hamstrings"],
    loadedJoints: ["knees", "ankles"],
    movementPattern: "squat" as const,
    modality: "strength" as const,
    movementTags: ["unilateral", "balance_challenge", "knee_dominant"],
    functionTags: [],
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "high" as const,
    equipment: ["dumbbells"],
    strengthLevel: "high" as const,
  },
  {
    name: "Dumbbell Shrugs",
    primaryMuscle: "traps" as const,
    secondaryMuscles: [],
    loadedJoints: [],
    movementPattern: "shoulder_isolation" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "scapular_control"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "very_low" as const,
    equipment: ["dumbbells"],
    strengthLevel: "low" as const,
  },
  {
    name: "Upright Row",
    primaryMuscle: "traps" as const,
    secondaryMuscles: ["delts", "biceps"],
    loadedJoints: ["shoulders"],
    movementPattern: "vertical_pull" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "scapular_control"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "low" as const,
    equipment: ["dumbbells"],
    strengthLevel: "low" as const,
  },
  {
    name: "Dumbbell Bridge Chest Press",
    primaryMuscle: "chest" as const,
    secondaryMuscles: ["triceps", "core"],
    loadedJoints: ["shoulders"],
    movementPattern: "horizontal_push" as const,
    modality: "strength" as const,
    movementTags: ["bilateral", "postural_control"],
    functionTags: [],
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "low" as const,
    equipment: ["dumbbells"],
    strengthLevel: "low" as const,
  },
  {
    name: "Spanish Lunge",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "hamstrings"],
    loadedJoints: ["hips", "knees"],
    movementPattern: "lunge" as const,
    modality: "mobility" as const,
    movementTags: ["unilateral", "hip_stability"],
    functionTags: ["rehab_friendly"],
    fatigueProfile: "low_local" as const,
    complexityLevel: "low" as const,
    equipment: ["bands"],
    strengthLevel: "low" as const,
  },
  {
    name: "Cross Cable Rear Delt Fly",
    primaryMuscle: "delts" as const,
    secondaryMuscles: ["traps", "upper_back"],
    loadedJoints: ["shoulders"],
    movementPattern: "shoulder_isolation" as const,
    modality: "strength" as const,
    movementTags: ["scapular_control", "bilateral"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["cable_machine"],
    strengthLevel: "low" as const,
  },
  {
    name: "Swiss Ball Plank on Bench",
    primaryMuscle: "core" as const,
    secondaryMuscles: ["shoulders"],
    loadedJoints: [],
    movementPattern: "core" as const,
    modality: "core" as const,
    movementTags: ["core_stability", "isometric_control", "balance_challenge"],
    functionTags: ["rehab_friendly"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["swiss_ball"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Hollow Body Hold",
    primaryMuscle: "core" as const,
    secondaryMuscles: [],
    loadedJoints: [],
    movementPattern: "core" as const,
    modality: "core" as const,
    movementTags: ["core_stability", "isometric_control"],
    functionTags: ["warmup_friendly"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: [],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Plank Shoulder Taps",
    primaryMuscle: "core" as const,
    secondaryMuscles: ["shoulders", "obliques"],
    loadedJoints: ["shoulders"],
    movementPattern: "core" as const,
    modality: "core" as const,
    movementTags: ["anti_rotation", "core_stability", "postural_control"],
    functionTags: ["warmup_friendly"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: [],
    strengthLevel: "low" as const,
  },
  {
    name: "Landmine Explosive Press",
    primaryMuscle: "shoulders" as const,
    secondaryMuscles: ["triceps", "core"],
    loadedJoints: ["shoulders"],
    movementPattern: "vertical_push" as const,
    modality: "power" as const,
    movementTags: ["explosive", "postural_control"],
    functionTags: [],
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "high" as const,
    equipment: ["barbell", "landmine"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Cable Rear Deadlift",
    primaryMuscle: "hamstrings" as const,
    secondaryMuscles: ["glutes", "lower_back"],
    loadedJoints: ["hips"],
    movementPattern: "hinge" as const,
    modality: "strength" as const,
    movementTags: ["hip_dominant", "postural_control"],
    functionTags: [],
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "moderate" as const,
    equipment: ["cable_machine"],
    strengthLevel: "low" as const,
  },
  {
    name: "Upside-Down Kettlebell Press (single arm)",
    primaryMuscle: "shoulders" as const,
    secondaryMuscles: ["triceps", "core"],
    loadedJoints: ["shoulders", "wrists"],
    movementPattern: "vertical_push" as const,
    modality: "stability" as const,
    movementTags: ["unilateral", "postural_control", "scapular_control"],
    functionTags: [],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["kettlebell"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Banded Suitcase Marches",
    primaryMuscle: "core" as const,
    secondaryMuscles: ["obliques"],
    loadedJoints: ["hips"],
    movementPattern: "carry" as const,
    modality: "stability" as const,
    movementTags: ["anti_rotation", "postural_control", "balance_challenge"],
    functionTags: ["warmup_friendly"],
    fatigueProfile: "moderate_local" as const,
    complexityLevel: "moderate" as const,
    equipment: ["bands", "dumbbells"],
    strengthLevel: "low" as const,
  },
  {
    name: "Barbell Reverse Lunges",
    primaryMuscle: "quads" as const,
    secondaryMuscles: ["glutes", "hamstrings"],
    loadedJoints: ["knees", "hips"],
    movementPattern: "lunge" as const,
    modality: "strength" as const,
    movementTags: ["unilateral", "knee_dominant", "hip_stability"],
    functionTags: ["foundational"],
    fatigueProfile: "high_systemic" as const,
    complexityLevel: "moderate" as const,
    equipment: ["barbell"],
    strengthLevel: "moderate" as const,
  },
  {
    name: "Kettlebell Swings",
    primaryMuscle: "glutes" as const,
    secondaryMuscles: ["hamstrings", "core"],
    loadedJoints: ["hips", "shoulders"],
    movementPattern: "hinge" as const,
    modality: "power" as const,
    movementTags: ["hip_dominant", "explosive", "postural_control"],
    functionTags: ["foundational"],
    fatigueProfile: "moderate_systemic" as const,
    complexityLevel: "moderate" as const,
    equipment: ["kettlebell"],
    strengthLevel: "moderate" as const,
  },
];

export async function POST() {
  try {
    const insertedExercises = await db.insert(exercises).values(allExercises).returning();
    
    return NextResponse.json({
      success: true,
      message: `Successfully inserted ${insertedExercises.length} exercises`,
      exercises: insertedExercises.map(ex => ({ id: ex.id, name: ex.name })),
    });
  } catch (error) {
    return NextResponse.json(
      {
        success: false,
        message: "Failed to insert exercises",
        error: error instanceof Error ? error.message : String(error),
      },
      { status: 500 }
    );
  }
}